### ISSUE TITLE
Double call to cmake needed for successful compilation

### ISSUE THREAD

**Issue by AlbanOdot** [STORM-IRIT/Radium-Releases#3]
Hello,

From a clean compilation
`git clone https://github.com/STORM-IRIT/Radium-Releases/`
`mkdir Radium-Releases/build`
`cd Radium-Releases/build`
`cmake ..`
`make`
The installation process stops at :

[ 37%] Completed 'radiumproject'
[ 50%] Built target radiumproject
[ 56%] Performing update step for 'radiumapps'
[ 62%] No patch step for 'radiumapps'
[ 68%] Performing configure step for 'radiumapps'
CMake Error at MainApplication/CMakeLists.txt:18 (find_package):
  By not providing "FindRadium.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Radium", but
  CMake did not find one.

  Could not find a package configuration file provided by "Radium" with any
  of the following names:

    RadiumConfig.cmake
    radium-config.cmake

  Add the installation prefix of "Radium" to CMAKE_PREFIX_PATH or set
  "Radium_DIR" to a directory containing one of the above files.  If "Radium"
  provides a separate development package or SDK, be sure it has been
  installed.

Quick / dirty fix is to call a second time cmake
`cmake .. -DCMAKE_PREFIX_PATH=PATH_TO_PROJECT/Radium-Releases/build/radiumproject-prefix/lib/cmake`
In order to setup the prefix path.
The make runs fine after this.

Have a good day.

**Comment by nmellado** [comment]
Hi @AlbanOdot 
Yes true, in fact we do not use the cmake script here but rather the github action, that's why I've missed it.
Thanks for the report, we will fix it.

**Comment by dlyr** [comment]
the CMakeLists.txt be removed in #5 , which solves this issue, sort of.
